site_description: Paisa is an open source personal finance manager. It helps you with tracking investments like mutual funds, stocks etc. It helps with expenses categorization, budgeting and money management in general.
site_author: Anantha Kumaran
site_name: Paisa
site_url: https://paisa.fyi
repo_url: https://github.com/ananthakumaran/paisa
repo_name: ananthakumaran/paisa
nav:
  - index.md
  - 'Getting Started':
    - getting-started/installation.md
    - getting-started/tutorial.md
  - 'Reference':
    - reference/accounts.md
    - reference/commodities.md
    - reference/journal.md
    - reference/allocation-targets.md
    - reference/budget.md
    - reference/bulk-edit.md
    - reference/import.md
    - reference/recurring.md
    - reference/config.md
    - 'Goals':
        - reference/goals/index.md
        - reference/goals/retirement.md
        - reference/goals/savings.md
    - reference/ledger-cli.md
    - reference/editor.md
    - reference/user-authentication.md
    - reference/analysis.md
    - 'Tax':
      - reference/tax/index.md
      - reference/tax/tax-harvesting.md
      - reference/tax/capital-gains.md
      - reference/tax/schedule-al.md
    - reference/changelog.md
  - 'Demo': 'https://demo.paisa.fyi'
  - faq.md
  - Blog:
    - blog/index.md
theme:
  custom_dir: overrides
  name: material
  favicon: images/favicon.png
  icon:
    logo: paisa/logo
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: indigo
      toggle:
        icon: material/moon-waning-crescent
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.keys
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/device-frames.min.css
  - stylesheets/extra.css

copyright: |
  Copyright Â© 2022 - 2023 Anantha Kumaran <br \> <a href="#__consent">Change cookie settings</a>
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ananthakumaran/paisa
    - icon: simple/matrix
      link: https://matrix.to/#/#paisa:matrix.org
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/PaisaFinanceApp
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@PaisaFinanceApp
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ananthakumaran/paisa
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-NL7XFHE65Z
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSejpTiljuhsviEvXFBN-Z5rJZ_dkXHV5RaZzqpyCAZF1nIFiQ/viewform?usp=pp_url&entry.1125403938={url}" target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - blog
hooks:
  - docs/lexer/hook.py
