[book]
authors = ["Anantha Kumaran"]
language = "en"
multilingual = false
src = "src"
title = "â‚¹ Paisa"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["./mdbook-admonish.css"]
