name: Release

on:
  push:
    branches:
      - ci/*
    tags:
      - '*'

jobs:
  linux-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix develop --command npm install
        nix develop --command npm run build
        nix develop --command go build
        cp paisa paisa-linux-amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mac-binary:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - run: |
        brew install --force --overwrite go sqlite3
        npm install
        npm run build
        go build
        cp paisa paisa-darwin-amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows-binary:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.1'
    - run: |
        choco install sqlite
        npm install
        npm run build
        go build
        cp paisa.exe paisa-windows-amd64.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
